# ignore all warnings from all pods
inhibit_all_warnings!

pod 'FLAnimatedImage', '~> 1.0'
pod 'Pop'
pod 'AYVibrantButton'
pod 'PBJVision'
pod 'PBJVideoPlayer'
pod 'NYTPhotoViewer'
pod 'FastttCamera'
pod 'Shimmer'
pod 'SCRecorder'
pod 'SVProgressHUD'
pod 'ParseUI'