inhibit_all_warnings!
use_frameworks!

#pod 'ParseUI', '~> 1.1.4'
pod 'ParseFacebookUtils'
pod 'FBSDKCoreKit', '~> 4.2.0'
pod 'PBJVision'
pod 'FLAnimatedImage', '~> 1.0'
pod 'MBProgressHUD'
pod 'SwiftMoment'
pod 'ParseUI'
pod 'WaitBlock'
pod 'jot'
pod 'Masonry', '~> 0.6.1'
